use andywang;
show tables;
select * from tables;



select * from book;
alter table book modify id 

#delete from book where id =28114;
/*
drop table book;
CREATE TABLE book(
   url                   VARCHAR(41) NOT NULL 
  ,tpl_name              VARCHAR(14) NOT NULL
  ,abstract              VARCHAR(121) NOT NULL
  ,id                    INTEGER  NOT NULL primary key
  ,title                 VARCHAR(45) NOT NULL
  ,more_url              VARCHAR(108)
  ,cover_url             VARCHAR(61)
  ,ratingvalue           NUMERIC(3,1)
  ,ratingcount           INTEGER 
  ,ratingstar_count      NUMERIC(3,1)
  ,ratingrating_info     VARCHAR(30)
  ,abstract_2            VARCHAR(30)
  ,interest              VARCHAR(30)
  ,extra_actions0color   VARCHAR(7)
  ,extra_actions0text    VARCHAR(7)
  ,extra_actions0url     VARCHAR(82)
);

#INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/series/28114','search_simple','电子工业出版社;电子工业 / 共3册 / 2015年出版',28114,'[丛书] Java技术大系',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/2696119/','search_subject','Joshua Bloch / Addison-Wesley / 2008-05-28 / USD 54.99',2696119,'Effective Java: Second Edition : Java','onclick="moreurl(this,{i:''0'',query:''java'',subject_id:''2696119'',from:''book_subject_search'',cat_id:''1001''})"','https://img3.doubanio.com/view/subject/m/public/s3259732.jpg',9.3,282,4.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/2130190/','search_subject','[美] Bruce Eckel / 陈昊鹏 / 机械工业出版社 / 2007-6 / 108.00元',2130190,'Java编程思想 （第4版）','onclick="moreurl(this,{i:''1'',query:''java'',subject_id:''2130190'',from:''book_subject_search'',cat_id:''1001''})"','https://img9.doubanio.com/view/subject/m/public/s27243455.jpg',9.1,3811,4.5,NULL,NULL,NULL,'#CF5B40','豆瓣书店有售','https://book.douban.com/subject/2130190/?channel=subject_list&platform=web');
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/10484692/','search_subject','Brian Goetz / Tim Peierls / Joshua Bloch / Joseph Bowbeer / David Holmes / Doug Lea / 童云兰 / 机械工业出版社华章公司 / 2012-2 / 69.00元',10484692,'Java并发编程实战','onclick="moreurl(this,{i:''2'',query:''java'',subject_id:''10484692'',from:''book_subject_search'',cat_id:''1001''})"','https://img3.doubanio.com/view/subject/m/public/s7663093.jpg',9,1259,4.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/3351237/','search_subject','韦斯 (Mark Allen Weiss) / 冯舜玺 / 机械工业出版社 / 2009-1-1 / 55.00元',3351237,'数据结构与算法分析 : Java语言描述','onclick="moreurl(this,{i:''3'',query:''java'',subject_id:''3351237'',from:''book_subject_search'',cat_id:''1001''})"','https://img3.doubanio.com/view/subject/m/public/s28318872.jpg',8.3,265,4,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/2000732/','search_subject','Kathy Sierra,Bert Bates 著 / 杨尊一 编译 张然等 改编 / 杨尊一 / 中国电力出版社 / 2007-2 / 79.00元',2000732,'Head First Java（第二版·中文版）','onclick="moreurl(this,{i:''4'',query:''java'',subject_id:''2000732'',from:''book_subject_search'',cat_id:''1001''})"','https://img9.doubanio.com/view/subject/m/public/s2171906.jpg',8.7,1249,4.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/3360807/','search_subject','Joshua Bloch / 俞黎敏 / 机械工业出版社 / 2009-1-1 / 52.00元',3360807,'Effective java 中文版（第2版）','onclick="moreurl(this,{i:''5'',query:''java'',subject_id:''3360807'',from:''book_subject_search'',cat_id:''1001''})"','https://img3.doubanio.com/view/subject/m/public/s3479802.jpg',9.1,1657,4.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/25828043/','search_subject','Charlie Hunt / Binu John / 柳飞 / 陆明刚 / 人民邮电出版社 / 2014-3 / 109.00 元',25828043,'Java性能优化权威指南 : Java性能优化权威指南','onclick="moreurl(this,{i:''6'',query:''java'',subject_id:''25828043'',from:''book_subject_search'',cat_id:''1001''})"','https://img1.doubanio.com/view/subject/m/public/s27219217.jpg',8.2,184,4,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/24722612/','search_subject','周志明 / 机械工业出版社 / 2013-9-1 / 79.00元',24722612,'深入理解Java虚拟机（第2版） : JVM高级特性与最佳实践','onclick="moreurl(this,{i:''7'',query:''java'',subject_id:''24722612'',from:''book_subject_search'',cat_id:''1001''})"','https://img9.doubanio.com/view/subject/m/public/s27458236.jpg',9,1702,4.5,NULL,NULL,NULL,'#973F31','豆瓣阅读电子版','https://read.douban.com/ebook/15233695/?dcs=search-buylink&dcm=douban&dct=24722612');
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/26880667/','search_subject','[美] 凯.S.霍斯特曼（Cay S. Horstmann） / 周立新 等 / 机械工业出版社 / 2016-9 / CNY 119.00',26880667,'Java核心技术·卷 I（原书第10版） : 基础知识','onclick="moreurl(this,{i:''8'',query:''java'',subject_id:''26880667'',from:''book_subject_search'',cat_id:''1001''})"','https://img9.doubanio.com/view/subject/m/public/s29063065.jpg',8.3,459,4,NULL,NULL,NULL,'#CF5B40','豆瓣书店有售','https://book.douban.com/subject/26880667/?channel=subject_list&platform=web');
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/6522893/','search_subject','周志明 / 机械工业出版社 / 2011-6 / 69.00元',6522893,'深入理解Java虚拟机 : JVM高级特性与最佳实践','onclick="moreurl(this,{i:''9'',query:''java'',subject_id:''6522893'',from:''book_subject_search'',cat_id:''1001''})"','https://img3.doubanio.com/view/subject/m/public/s6564370.jpg',8.6,777,4.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/6529833/','search_subject','（美）  Y. Daniel Liang / 李娜 / 机械工业出版社 / 2011-6 / 75.00元',6529833,'Java语言程序设计 : 基础篇 (原书第8版)','onclick="moreurl(this,{i:''10'',query:''java'',subject_id:''6529833'',from:''book_subject_search'',cat_id:''1001''})"','https://img1.doubanio.com/view/subject/m/public/s6520557.jpg',8.7,269,4.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/3146174/','search_subject','Cay S. Horstmann / Gary Cornell / 杜永萍 / 邝劲筠 / 叶乃文 / 机械工业出版社 / 2008-6 / 98.00元',3146174,'JAVA核心技术（卷1）','onclick="moreurl(this,{i:''11'',query:''java'',subject_id:''3146174'',from:''book_subject_search'',cat_id:''1001''})"','https://img3.doubanio.com/view/subject/m/public/s23284090.jpg',9,611,4.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/1103015/','search_subject','（美）Joshua Bloch / 潘爱民 / 机械工业出版社 / 2003-1 / 39.00元',1103015,'Effective Java 中文版','onclick="moreurl(this,{i:''12'',query:''java'',subject_id:''1103015'',from:''book_subject_search'',cat_id:''1001''})"','https://img1.doubanio.com/view/subject/m/public/s2008079.jpg',8.9,771,4.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/26555197/','search_subject','高洪岩 / 机械工业出版社 / 2015-6-1 / 69.00',26555197,'Java多线程编程核心技术 : Java Multi-thread Programming','onclick="moreurl(this,{i:''13'',query:''java'',subject_id:''26555197'',from:''book_subject_search'',cat_id:''1001''})"','https://img9.doubanio.com/view/subject/m/public/s28238985.jpg',5,191,2.5,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO book(url,tpl_name,abstract,id,title,more_url,cover_url,ratingvalue,ratingcount,ratingstar_count,ratingrating_info,abstract_2,interest,extra_actions0color,extra_actions0text,extra_actions0url) VALUES ('https://book.douban.com/subject/25762168/','search_subject','（美）Cay S. Horstmann / （美）Gary Cornell / 周立新 / 陈波 / 叶乃文 / 邝劲筠 / 杜永萍 / 机械工业出版社 / 2013-11-1 / 119.00',25762168,'Java核心技术·卷1：基础知识（原书第9版）','onclick="moreurl(this,{i:''14'',query:''java'',subject_id:''25762168'',from:''book_subject_search'',cat_id:''1001''})"','https://img3.doubanio.com/view/subject/m/public/s27123141.jpg',8.3,532,4,NULL,NULL,NULL,NULL,NULL,NULL);
*/
